### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by matkoch** [ItEndsWithTens/Arbatel#1]
https://github.com/ItEndsWithTens/Arbatel/blob/37d23ff8271be18d08d0eb2b05723cf63ed3d31f/build/Build.cs#L246

These lines can be written much better now using `When` and `CombineWith`. See http://www.nuke.build/docs/authoring-builds/cli-tools.html

**Comment by ItEndsWithTens** [comment]
Ooh, those look great! I'll get to working on that soon; thanks for taking the time to point me in the right direction.

**Comment by ItEndsWithTens** [comment]
This should be substantially improved with commit 5d87105 and later; thanks again for the heads up! Very happy to have found Nuke, these build scripts are a pleasure to work with.

**Comment by matkoch** [comment]
You're welcome :)

https://github.com/ItEndsWithTens/Arbatel/commit/5d87105fc37bcd46777062680a08eb0d41927d85#diff-e9f1a0f7fa23a66e0a5b94f696c7e12fR305

For this you could use `PathExecutableAttribute`.

https://github.com/ItEndsWithTens/Arbatel/commit/5d87105fc37bcd46777062680a08eb0d41927d85#diff-e9f1a0f7fa23a66e0a5b94f696c7e12fR160

`settings` is already a clean `new MSBuildSettings()` object

https://github.com/ItEndsWithTens/Arbatel/blob/master/build/Build.cs#L138-L157

that part looks overly complicated to me. Isn't it the same as https://github.com/nuke-build/common/blob/develop/build/Build.cs#L62 ?

Feel free to ignore my comments :D

**Comment by ItEndsWithTens** [comment]
I'll look at PathExecutableAttribute, thanks! It just didn't even occur to me, for some reason, that I could use Nuke to execute a Python script. Tunnel vision, I guess.

Same for settings => new MSBuildSettings(), that's more cargo cult code than anything; I'm still rather inexperienced in software development, as I'd imagine is obvious, so I find myself doing that sort of thing now and again.

The file deletion stuff did seem excessive to me, and I initially tried a simple DeleteDirectories, but if I remember correctly I ran into errors during the build suggesting the folders couldn't be deleted because they weren't empty. I wouldn't be surprised to find that was a side effect of me doing something stupid, of course, so I'll give it another shot and see how things work out.

I appreciate the attention to this build script, and I'm embarrassed to be making your build system look bad by association with my dopey oversights; I won't ignore any of these points!

**Comment by matkoch** [comment]
>  I'm embarrassed to be making your build system look bad

I'm not at all thinking that way :) I took some time adding notes because your build is not as simple as many others. Only by looking at what people do, the framework can get better. So thanks for your feedback :)

**Comment by matkoch** [comment]
https://github.com/ItEndsWithTens/Arbatel/commit/2795d017bfb0bfcb3b0d488d36dd456346a1fe2a

You can pass `framework` to `GetMSBuildProject`. Would that help?

**Comment by ItEndsWithTens** [comment]
I tried that earlier but it didn't seem to make a difference. To be certain I just tried again, changing the GetOutputPath method back to this:

```
Project n = Solution.GetProject(name);

Microsoft.Build.Evaluation.Project m = n.GetMSBuildProject(Configuration, "net471");
Microsoft.Build.Evaluation.ProjectProperty o = m.GetProperty("OutputPath");

return n.Directory / o.EvaluatedValue;
```

Running the build script in macOS throws the same error I get when I don't specify a framework, and that commit 2795d01 was intended to address:
> "The imported project "/usr/local/share/dotnet/sdk/2.1.302/Xamarin/Mac/Xamarin.Mac.CSharp.targets" was not found."

The Eto GUI framework has support for making Mac .app bundles out of your application, either one that depends on the Mono framework, like my Arbatel.Mac project, or one that's entirely self contained by bundling Mono into the .app itself, like my Arbatel.XamMac project. There are various .targets files that each Eto Nuget package provides, depending on the platform, and that Xamarin.Mac.CSharp.targets file is one of them, as I understand it. My .Mac project builds fine, only the .XamMac variant fails.

That it's looking in dotnet/sdk is what made me suspect, perhaps naively, that it's related to the difference between .NET Framework and .NET Core. Am I not specifying the framework properly when using GetMSBuildProject? Or could that error be coming from somewhere else?

You're welcome for the feedback! I'm happy to help, when I can; I'm just finishing up work on the other issues you mentioned, I should be able to push them soon and be back presently with a separate comment.

**Comment by ItEndsWithTens** [comment]
Okay, more changes pushed! Commit 39e6cc6 makes a few of the suggested tweaks, with a couple of notable alterations:

- I experimented with a Tool member named DmgBuild, annotated as [PathExecutable], and had success in macOS, but the code fails elsewhere, since dmgbuild doesn't make sense anywhere else; it depends on hdiutil for creating .dmg files, and that's not going to be available on other platforms. Although Windows and Linux can run a Python script like dmgbuild itself, I'd rather not make my code dependent on that unnecessarily. I did still switch to ProcessTasks.StartProcess for that step, though, for the sake of using Nuke to its fullest. :)

- [Line 241](https://github.com/ItEndsWithTens/Arbatel/blob/39e6cc6a5154565e3e96c14b221c8ce43638ebb6/build/Build.cs#L241) may seem odd, but in testing this I ran into what I believe was the issue I mentioned earlier that originally led me to that complicated Clean step with the file globbing and sorting: at least in Windows 10 1809, if I have a Windows Explorer window open to the directory that EnsureCleanDirectory is targeting, said method will delete the directory but not recreate it, leading my SharpCompress archive.SaveTo calls to fail when the directory isn't found. I can consistently reproduce the behavior, too:
  - In any project using Nuke, set a breakpoint on a line of code that calls EnsureCleanDirectory.
  - Debug the code, stopping at that breakpoint. In Windows Explorer, open the directory that's about to be cleaned, and leave the window open during the next step.
  - Back in your debugger, step over the EnsureCleanDirectory line. Windows Explorer should refresh, and at the same time bump you up one directory level. The directory you were inside should be gone.

  Repeating those steps but without going down into the directory shows that it gets deleted and recreated without issue. Only having an Explorer window open seems to trigger this.

  I can open a new issue in the Nuke repository, if that would be helpful, but in case this is something I'm doing wrong, or just a Windows quirk that's out of your control, I didn't want to jump right to that. Does this sound like something worth a bug report?
